In [32]:
import pandas as pd 
import numpy as np
import scipy.stats as stats

In [26]:
data=pd.read_csv(r"C:\Users\sudarson.SUDARSON\Downloads\test mach learn\Paper2\credit_card.csv").replace(np.NaN,"unknown")

In [27]:
data.head()

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,C10001,40.900749,0.818182,95.40,0.00,95.4,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,1000.0,201.802084,139.509787,0.000000,12
1,C10002,3202.467416,0.909091,0.00,0.00,0.0,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222,12
2,C10003,2495.148862,1.000000,773.17,773.17,0.0,0.000000,1.000000,1.000000,0.000000,0.000000,0,12,7500.0,622.066742,627.284787,0.000000,12
3,C10004,1666.670542,0.636364,1499.00,1499.00,0.0,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,unknown,0.000000,12
4,C10005,817.714335,1.000000,16.00,16.00,0.0,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,678.334763,244.791237,0.000000,12

In [28]:
col = list(data.columns)
col

['CUST_ID',
 'BALANCE',
 'BALANCE_FREQUENCY',
 'PURCHASES',
 'ONEOFF_PURCHASES',
 'INSTALLMENTS_PURCHASES',
 'CASH_ADVANCE',
 'PURCHASES_FREQUENCY',
 'ONEOFF_PURCHASES_FREQUENCY',
 'PURCHASES_INSTALLMENTS_FREQUENCY',
 'CASH_ADVANCE_FREQUENCY',
 'CASH_ADVANCE_TRX',
 'PURCHASES_TRX',
 'CREDIT_LIMIT',
 'PAYMENTS',
 'MINIMUM_PAYMENTS',
 'PRC_FULL_PAYMENT',
 'TENURE']

<h1>missing value<h1>

In [31]:
for i in range(0,len(col)):
    if(data[data[col[i]]=='unknown'].shape[0]!=0):
        print(col[i],data[data[col[i]]=='unknown'].shape[0])

CREDIT_LIMIT 1
MINIMUM_PAYMENTS 313

In [33]:
data.shape

(8950, 18)

In [36]:
data=pd.DataFrame(np.random.randint(0,10,size=(data.shape)),columns=col)

In [37]:
data.apply(stats.zscore)

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,-0.879964,1.242135,-0.175358,-0.874360,-0.524302,0.170331,-0.515429,1.564674,-1.216675,1.562309,-0.856275,0.878773,0.169025,0.871663,0.162545,1.207272,-1.212844,-1.211748
1,0.864295,0.891648,-0.872273,1.219146,0.873211,0.170331,-0.166587,-0.521040,1.572935,1.213040,1.226147,0.530301,0.516470,0.525058,-0.887333,0.515747,1.226080,0.530164
2,1.213147,0.541160,-0.175358,0.521310,-0.174923,-0.872631,0.879940,0.869436,-0.170571,0.863770,1.573218,-0.515116,0.169025,-0.168152,0.862464,-1.213067,-1.212844,-0.166601
3,-0.879964,-1.211277,0.870015,1.568063,-1.572436,-0.177323,0.531098,1.564674,-0.867974,0.165230,0.184936,-0.166644,0.863914,0.178453,1.212423,-0.867304,-1.212844,-1.211748
4,1.213147,-0.860789,-1.569189,0.521310,1.571968,1.560947,-1.561956,-1.216278,-1.565377,-0.184040,-0.509205,-0.515116,-1.220754,-0.168152,1.562383,1.553035,-0.864427,1.575311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,0.864295,-1.561764,0.173100,1.219146,-0.524302,-0.872631,-0.166587,0.869436,-1.565377,-1.581119,-0.856275,0.181829,-0.178420,-1.554572,-1.587251,1.207272,-0.864427,-1.211748
8946,0.166591,1.592623,0.173100,-0.525443,-1.223058,0.170331,-1.213114,0.521817,-1.216675,-0.882580,1.573218,0.181829,1.558804,-0.514757,-0.187414,-1.558830,0.529245,0.181782
8947,1.213147,0.891648,0.521557,-1.572196,-1.572436,1.213293,-0.515429,-1.563897,0.526831,-0.882580,-0.162134,-0.515116,1.558804,-0.514757,-1.237292,0.515747,1.226080,-0.514983
8948,-1.577667,0.541160,-0.872273,-1.572196,-0.524302,1.213293,-0.515429,0.521817,1.572935,-1.581119,1.226147,1.575718,1.558804,-0.168152,0.512505,1.553035,0.877663,0.530164
8949,-0.531112,-1.211277,1.218473,-0.874360,0.174455,1.213293,-1.213114,-0.173421,0.526831,0.165230,-1.550416,1.575718,-0.178420,1.564873,1.562383,-0.521542,0.180827,1.226929